using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using FishMMO.Shared;
using FishMMO.Shared.WorldDesign;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using Debug = UnityEngine.Debug;
using Object = UnityEngine.Object;

namespace FishMMO.Client
{
	/// <summary>
	/// Compiles, in edit mode and in the background, the shader variants Play will ask for — so pressing Play does not
	/// wait on them.
	/// </summary>
	/// <remarks>
	/// <para>
	/// <b>Why Play compiled shaders.</b> The editor compiles a variant the first time something draws with it. The GPU
	/// terrain renderer's indirect twins (FishMMO/Vegetation Indirect, FishMMO/Weather Lit Indirect) and their
	/// procedural-instancing variants are drawn only in play mode, and TerrainGpuRenderer warms its collection only in a
	/// player (in the editor ShaderVariantCollection.WarmUp compiles synchronously: a 5.7 s first frame). Every edit to a
	/// shader or an include they share threw their compiled variants away, and the next Play spent 20 s compiling them
	/// behind placeholders (StartupTimeline, 2026-10-08).
	/// </para>
	/// <para>
	/// <b>Which variants.</b> A variant is the material's keywords AND the ones URP turns on as it draws (shadow cascades,
	/// soft shadows, the light loop, fog, LOD cross-fade, procedural instancing), so no material on disk says which are
	/// needed. The editor itself knows: it tracks every variant drawn in the session (what Graphics Settings' "Save to
	/// asset…" exports). The record is cleared as Play starts, so when Play ends it holds that Play's variants alone; it is
	/// saved and every variant of a project or package shader is merged into <see cref="ListPath"/> (Library: this
	/// machine's own, regenerated by playing), stamped with that Play.
	/// </para>
	/// <para>
	/// <b>Forgetting.</b> The list used to only grow: every shadow, cookie, fog and occlusion combination a quality
	/// setting ever drew stayed in it, and each was compiled again after every shader edit, into a shader cache that grew
	/// with it. A variant no Play has drawn in the last <see cref="KeepPlays"/> is dropped, and so is one whose shader is
	/// gone or no longer declares one of its keywords (2026-10-10). One still in use is learned again the next time it is
	/// drawn.
	/// </para>
	/// <para>
	/// <b>Warming.</b> On editor load, after any shader or shader include is imported, and from the dashboard: each listed
	/// variant's passes that are not compiled are requested with <see cref="ShaderUtil.CompilePass"/>, not forced, so the
	/// editor's background compiler takes them and nothing blocks. A few dozen are requested per editor frame. Never in
	/// play mode, in batch mode, or with asynchronous shader compilation switched off (Project Settings → Editor), where
	/// each request would block.
	/// </para>
	/// </remarks>
	[InitializeOnLoad]
	public static class ShaderPrewarm
	{
		/// <summary>
		/// The learned variants: a "#plays" header with the number of Plays learned from, then one per line — shader name,
		/// pass type, sorted keywords and the Play that last drew it, tab-separated.
		/// </summary>
		public const string ListPath = "Library/FishMMO/ShaderWarmList.txt";

		/// <summary>How many Plays a learned variant is kept without being drawn again.</summary>
		public const int KeepPlays = 5;

		private const string PlaysHeader = "#plays";

		/// <summary>
		/// Where the editor's record is saved for reading (it writes an asset, so under Assets: the gitignored generated
		/// folder), deleted straight after.
		/// </summary>
		private const string CapturePath = ProceduralArtCatalogue.Root + "/Variants/_PlayModeVariants.shadervariants";

		private const int RequestsPerFrame = 32;
		private const string AutoKey = "FishMMO.ShaderPrewarm.Auto";

		/// <summary>Whether the editor warms by itself (on load and after shader imports). On by default; per machine.</summary>
		public static bool Auto
		{
			get => EditorPrefs.GetBool(AutoKey, true);
			set => EditorPrefs.SetBool(AutoKey, value);
		}

		private readonly struct Request
		{
			public readonly Material Material;
			public readonly int Pass;

			public Request(Material material, int pass)
			{
				Material = material;
				Pass = pass;
			}
		}

		private static readonly Queue<Request> queue = new Queue<Request>();
		private static readonly List<Material> materials = new List<Material>();
		private static bool running;
		private static bool scheduled;
		private static int requested, alreadyCompiled, known;
		private static string reason;
		private static readonly Stopwatch clock = new Stopwatch();

		static ShaderPrewarm()
		{
			EditorApplication.playModeStateChanged -= OnPlayModeChanged;
			EditorApplication.playModeStateChanged += OnPlayModeChanged;
			if (Auto)
			{
				Schedule("editor load");
			}
		}

		[DashboardTool(DashboardToolAttribute.Maintenance, "Warm shaders now", Section = "Diagnostics", Order = 1,
			Tooltip = "Compiles, in the background, every shader variant Play has used on this machine that is not compiled now, so the next Play does not wait on them. Learned each time Play ends (Library/FishMMO/ShaderWarmList.txt).")]
		public static void WarmNow()
		{
			Start("dashboard");
		}

		[DashboardTool(DashboardToolAttribute.Maintenance, "Toggle automatic shader warming", Section = "Diagnostics", Order = 2,
			Tooltip = "Warms the learned shader variants by itself on editor load and after any shader or include changes. On by default; remembered for this machine.")]
		public static void ToggleAuto()
		{
			Auto = !Auto;
			Debug.Log(Auto
				? "[Shader prewarm] Automatic: on (editor load and shader imports)."
				: "[Shader prewarm] Automatic: off (Dashboard → Maintenance → Warm shaders now still works).");
		}

		/// <summary>Warms on the next idle editor frame (shader imports arrive in bursts: one run for the burst).</summary>
		internal static void Schedule(string why)
		{
			if (scheduled || Application.isBatchMode)
			{
				return;
			}
			scheduled = true;
			EditorApplication.delayCall += () =>
			{
				scheduled = false;
				Start(why);
			};
		}

		private static void OnPlayModeChanged(PlayModeStateChange change)
		{
			if (change == PlayModeStateChange.ExitingEditMode)
			{
				Stop(false);
				ClearRecord();
			}
			else if (change == PlayModeStateChange.EnteredEditMode)
			{
				Learn();
				if (Auto)
				{
					Schedule("after Play");
				}
			}
		}

		// ── Learning ───────────────────────────────────────────────────

		/// <summary>
		/// Empties the editor's record of variants drawn, so what is saved when Play ends is that Play's own and not
		/// everything drawn since the editor started (which stamped long-gone variants as freshly used).
		/// </summary>
		private static void ClearRecord()
		{
			MethodInfo clear = typeof(ShaderUtil).GetMethod("ClearCurrentShaderVariantCollection", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
			if (clear == null)
			{
				Debug.LogWarning("[Shader prewarm] This editor has no ShaderUtil.ClearCurrentShaderVariantCollection: Play's record will include what edit mode drew.");
				return;
			}
			clear.Invoke(null, null);
		}

		/// <summary>Saves the editor's record of the variants this Play drew, stamps them in the list and drops stale ones.</summary>
		private static void Learn()
		{
			MethodInfo save = typeof(ShaderUtil).GetMethod("SaveCurrentShaderVariantCollection", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, null, new[] { typeof(string) }, null);
			if (save == null)
			{
				Debug.LogWarning("[Shader prewarm] This editor has no ShaderUtil.SaveCurrentShaderVariantCollection: nothing learned from Play.");
				return;
			}
			WarmList list = WarmList.Read();
			int play = list.Plays + 1;
			int added = 0;
			try
			{
				Directory.CreateDirectory(Path.GetDirectoryName(CapturePath));
				save.Invoke(null, new object[] { CapturePath });
				AssetDatabase.ImportAsset(CapturePath, ImportAssetOptions.ForceSynchronousImport);
				var collection = AssetDatabase.LoadAssetAtPath<ShaderVariantCollection>(CapturePath);
				if (collection == null)
				{
					Debug.LogWarning($"[Shader prewarm] The editor's variant record did not save to {CapturePath}: nothing learned from Play.");
					return;
				}
				var serialized = new SerializedObject(collection);
				SerializedProperty shaders = serialized.FindProperty("m_Shaders");
				for (int i = 0; shaders != null && i < shaders.arraySize; i++)
				{
					SerializedProperty pair = shaders.GetArrayElementAtIndex(i);
					var shader = pair.FindPropertyRelative("first").objectReferenceValue as Shader;
					// Built-in shaders (no asset) are compiled with the editor; everything with an asset path, ours and
					// URP's, is what Play compiles.
					if (shader == null || string.IsNullOrEmpty(AssetDatabase.GetAssetPath(shader)) || AssetDatabase.GetAssetPath(shader).StartsWith("Resources/unity_builtin", StringComparison.Ordinal))
					{
						continue;
					}
					SerializedProperty variants = pair.FindPropertyRelative("second.variants");
					for (int v = 0; variants != null && v < variants.arraySize; v++)
					{
						SerializedProperty variant = variants.GetArrayElementAtIndex(v);
						string keywords = variant.FindPropertyRelative("keywords").stringValue ?? string.Empty;
						int passType = variant.FindPropertyRelative("passType").intValue;
						if (!list.LastSeen.ContainsKey(Line(shader.name, passType, keywords)))
						{
							added++;
						}
						list.LastSeen[Line(shader.name, passType, keywords)] = play;
					}
				}
			}
			catch (Exception e)
			{
				Debug.LogWarning($"[Shader prewarm] Could not read the editor's variant record: {e.Message}");
				return;
			}
			finally
			{
				if (File.Exists(CapturePath))
				{
					AssetDatabase.DeleteAsset(CapturePath);
				}
			}
			list.Plays = play;
			int aged = list.Forget(line => play - list.LastSeen[line] >= KeepPlays);
			int stale = list.Forget(line => !StillDeclared(line));
			list.Write();
			if (added > 0 || aged > 0 || stale > 0)
			{
				Debug.Log($"[Shader prewarm] Learned {added} new shader variant(s) from Play; dropped {aged} not drawn in the last {KeepPlays} Plays and {stale} whose shader or keywords are gone ({list.LastSeen.Count} known).");
			}
		}

		/// <summary>One list line's variant: the keywords sorted, so the same set is one key whatever order Unity wrote it in.</summary>
		public static string Line(string shader, int passType, string keywords)
		{
			string[] sorted = (keywords ?? string.Empty).Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
			Array.Sort(sorted, StringComparer.Ordinal);
			return shader + "\t" + passType + "\t" + string.Join(" ", sorted);
		}

		/// <summary>
		/// Whether a variant's shader still exists and still declares each of its keywords. A shader that fails to compile
		/// is given the benefit of the doubt: mid-edit, it may declare nothing at all.
		/// </summary>
		private static bool StillDeclared(string line)
		{
			string[] parts = line.Split('\t');
			Shader shader = Shader.Find(parts[0]);
			if (shader == null)
			{
				return false;
			}
			if (ShaderUtil.ShaderHasError(shader))
			{
				return true;
			}
			var declared = new HashSet<string>(shader.keywordSpace.keywordNames, StringComparer.Ordinal);
			foreach (string keyword in parts[2].Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries))
			{
				if (!declared.Contains(keyword))
				{
					return false;
				}
			}
			return true;
		}

		/// <summary>The list file: each variant's key (<see cref="Line"/>) and the Play that last drew it.</summary>
		private sealed class WarmList
		{
			public int Plays;
			public readonly Dictionary<string, int> LastSeen = new Dictionary<string, int>(StringComparer.Ordinal);

			public static WarmList Read()
			{
				var list = new WarmList();
				if (!File.Exists(ListPath))
				{
					return list;
				}
				foreach (string line in File.ReadAllLines(ListPath))
				{
					if (string.IsNullOrWhiteSpace(line))
					{
						continue;
					}
					string[] parts = line.Split('\t');
					if (parts[0] == PlaysHeader)
					{
						int.TryParse(parts.Length > 1 ? parts[1] : null, out list.Plays);
						continue;
					}
					if (parts.Length < 3 || !int.TryParse(parts[1], out _))
					{
						continue;
					}
					// The old list had no stamp: last seen before any counted Play, so it ages out like the rest.
					int seen = parts.Length > 3 && int.TryParse(parts[3], out int stamp) ? stamp : 0;
					list.LastSeen[parts[0] + "\t" + parts[1] + "\t" + parts[2]] = seen;
				}
				return list;
			}

			/// <summary>Removes the variants the test picks; how many.</summary>
			public int Forget(Func<string, bool> stale)
			{
				List<string> gone = LastSeen.Keys.Where(stale).ToList();
				foreach (string line in gone)
				{
					LastSeen.Remove(line);
				}
				return gone.Count;
			}

			public void Write()
			{
				Directory.CreateDirectory(Path.GetDirectoryName(ListPath));
				IEnumerable<string> lines = LastSeen.OrderBy(e => e.Key, StringComparer.Ordinal).Select(e => e.Key + "\t" + e.Value);
				File.WriteAllLines(ListPath, new[] { PlaysHeader + "\t" + Plays }.Concat(lines));
			}
		}

		// ── Warming ────────────────────────────────────────────────────

		private static void Start(string why)
		{
			if (Application.isBatchMode || EditorApplication.isPlayingOrWillChangePlaymode)
			{
				return;
			}
			if (!EditorSettings.asyncShaderCompilation)
			{
				Debug.Log("[Shader prewarm] Skipped: asynchronous shader compilation is off (Project Settings → Editor), so every request would block the editor.");
				return;
			}
			Stop(false);
			reason = why;
			requested = alreadyCompiled = known = 0;
			// A shader edit can take keywords away: those variants are dropped before anything is compiled for them.
			WarmList list = WarmList.Read();
			int stale = list.Forget(line => !StillDeclared(line));
			if (stale > 0)
			{
				list.Write();
				Debug.Log($"[Shader prewarm] Dropped {stale} learned variant(s) whose shader or keywords are gone ({list.LastSeen.Count} known).");
			}
			var shaders = new Dictionary<string, Shader>(StringComparer.Ordinal);
			foreach (string line in list.LastSeen.Keys)
			{
				string[] parts = line.Split('\t');
				if (parts.Length != 3 || !int.TryParse(parts[1], out int passTypeValue))
				{
					continue;
				}
				if (!shaders.TryGetValue(parts[0], out Shader shader))
				{
					shaders[parts[0]] = shader = Shader.Find(parts[0]);
				}
				if (shader == null || !shader.isSupported)
				{
					continue;
				}
				known++;
				var material = new Material(shader)
				{
					hideFlags = HideFlags.HideAndDontSave,
					shaderKeywords = parts[2].Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries),
				};
				materials.Add(material);
				var passType = (PassType)passTypeValue;
				for (int p = 0; p < material.passCount; p++)
				{
					string lightMode = shader.FindPassTagValue(p, new ShaderTagId("LightMode")).name;
					if ((ProceduralArtVariants.PassTypeOf(lightMode) ?? PassType.Meta) == passType)
					{
						queue.Enqueue(new Request(material, p));
					}
				}
			}
			if (queue.Count == 0)
			{
				Stop(false);
				if (why == "dashboard")
				{
					Debug.Log($"[Shader prewarm] Nothing to warm yet: Play once and the variants it uses are learned ({ListPath}).");
				}
				return;
			}
			running = true;
			clock.Restart();
			EditorApplication.update -= Tick;
			EditorApplication.update += Tick;
		}

		private static void Tick()
		{
			if (!running || EditorApplication.isPlayingOrWillChangePlaymode)
			{
				Stop(false);
				return;
			}
			if (EditorApplication.isCompiling || EditorApplication.isUpdating)
			{
				return;
			}
			for (int n = 0; n < RequestsPerFrame && queue.Count > 0; n++)
			{
				Request r = queue.Dequeue();
				if (r.Material == null)
				{
					continue;
				}
				if (ShaderUtil.IsPassCompiled(r.Material, r.Pass))
				{
					alreadyCompiled++;
					continue;
				}
				ShaderUtil.CompilePass(r.Material, r.Pass, false);
				requested++;
			}
			// The materials are kept until the background compiler has finished with them.
			if (queue.Count == 0 && !ShaderUtil.anythingCompiling)
			{
				Stop(true);
			}
		}

		private static void Stop(bool finished)
		{
			if (finished && (requested > 0 || reason == "dashboard"))
			{
				Debug.Log($"[Shader prewarm] {reason}: {known} learned variant(s); {requested} pass(es) compiled in the background, {alreadyCompiled} already compiled; {clock.Elapsed.TotalSeconds:0.0} s.");
			}
			running = false;
			EditorApplication.update -= Tick;
			queue.Clear();
			foreach (Material m in materials)
			{
				if (m != null)
				{
					Object.DestroyImmediate(m);
				}
			}
			materials.Clear();
		}
	}

	/// <summary>Re-warms after a shader or a shader include is imported (an include's edit recompiles every shader that uses it).</summary>
	internal sealed class ShaderPrewarmImportWatch : AssetPostprocessor
	{
		private static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
		{
			if (!ShaderPrewarm.Auto)
			{
				return;
			}
			foreach (string path in imported)
			{
				if (path.EndsWith(".shader", StringComparison.OrdinalIgnoreCase) || path.EndsWith(".hlsl", StringComparison.OrdinalIgnoreCase)
					|| path.EndsWith(".cginc", StringComparison.OrdinalIgnoreCase) || path.EndsWith(".shadergraph", StringComparison.OrdinalIgnoreCase))
				{
					ShaderPrewarm.Schedule("shader import");
					return;
				}
			}
		}
	}
}
