using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.ResourceManagement.AsyncOperations;
using FishMMO.Logging;
using FishMMO.Shared.Core;

namespace FishMMO.Shared
{
	/// <summary>
	/// Everything about a dungeon that is the same for every instance of it: how it is described
	/// to a player standing at the entrance, and the difficulties it can be run at.
	/// </summary>
	/// <remarks>
	/// <para>
	/// Separate from <c>WorldSceneDetails</c>, which is regenerated by scanning the scene assets
	/// and would overwrite anything authored by hand, and separate from the
	/// <see cref="DungeonEntrance"/> itself, so several entrances into the same dungeon describe
	/// it identically. Assigned on the entrance; resolved on the client by template ID out of the
	/// shared cache, so the description, the artwork and the difficulty list all travel as one
	/// <c>int</c>.
	/// </para>
	/// <para>
	/// <b>The difficulty list is per dungeon.</b> There is no global set of difficulty levels and
	/// no enum to keep in step: a dungeon declares as many as it wants, in its own order, with its
	/// own rules. An instance records the index it was opened at, which is meaningful only
	/// alongside the dungeon that defined the list — so reordering this list renames the
	/// difficulty of every instance already open at that index, and entries should be appended
	/// rather than inserted once a dungeon is live.
	/// </para>
	/// </remarks>
	[CreateAssetMenu(fileName = "New Dungeon", menuName = "FishMMO/World/Dungeon", order = 1)]
	public class DungeonTemplate : CachedScriptableObject<DungeonTemplate>, ICachedObject
	{
		/// <summary>Display name of the dungeon. Falls back to the asset name when empty.</summary>
		[Tooltip("Display name shown in the dungeon finder header. Defaults to the asset name.")]
		public string DisplayName;

		/// <summary>
		/// Name of the dungeon scene this template describes. Must match the entrance's
		/// <c>DungeonName</c>.
		/// </summary>
		/// <remarks>
		/// The entrance points at the template; this points back. The reverse direction is what
		/// the scene server hosting a running instance has to follow: it knows the scene it loaded
		/// and the difficulty index recorded on the row, and there is no entrance object anywhere
		/// in the process to ask. Without it, an instance could be run but not described — no
		/// difficulty name for its panel and, more seriously, no ruleset to apply to what spawns
		/// inside it.
		/// <para>
		/// Leaving it empty is a working configuration for a dungeon reached only through an
		/// entrance; it costs the difficulty name in the instance panel and the difficulty's
		/// effects on the run.
		/// </para>
		/// </remarks>
		[Tooltip("Scene name of the dungeon. Must match the entrance's Dungeon Name.")]
		public string DungeonSceneName;

		/// <summary>Description shown in the dungeon finder above the instance list.</summary>
		[Tooltip("Description shown in the dungeon finder, above the instance list.")]
		[TextArea(3, 6)]
		public string Description;

		/// <summary>Addressable reference to the dungeon's artwork.</summary>
		[Tooltip("Artwork shown beside the description in the dungeon finder.")]
		public AssetReferenceSprite IconReference;

		/// <summary>
		/// Difficulties this dungeon offers, in the order they are presented.
		/// </summary>
		/// <remarks>
		/// An empty list means the dungeon has exactly one, unnamed difficulty at index 0 with
		/// default rules — see <see cref="GetDifficulty"/>. That is what an entrance with no
		/// template configured behaves as, so a dungeon authored before this system existed keeps
		/// working unchanged.
		/// </remarks>
		[Tooltip("Difficulties this dungeon offers. Empty means a single default difficulty.")]
		public List<DungeonDifficultyDefinition> Difficulties = new List<DungeonDifficultyDefinition>();

		/// <summary>The loaded artwork. Only available on the client after OnLoad completes.</summary>
		[System.NonSerialized]
		private Sprite loadedIcon;

		/// <summary>The dungeon's artwork, loaded at runtime on the client.</summary>
		public Sprite Icon { get { return this.loadedIcon; } }

		/// <inheritdoc />
		public string Name { get { return this.name; } }

		/// <summary>
		/// The name to show for this dungeon.
		/// </summary>
		public string ResolvedDisplayName => string.IsNullOrWhiteSpace(DisplayName) ? name : DisplayName;

		/// <summary>
		/// How many difficulties this dungeon offers. Never less than one.
		/// </summary>
		public int DifficultyCount => Difficulties == null || Difficulties.Count < 1 ? 1 : Difficulties.Count;

		/// <summary>
		/// The rules for one difficulty index.
		/// </summary>
		/// <remarks>
		/// Never returns null and never throws. An index outside the list — a client asking for a
		/// difficulty this dungeon does not offer, or an instance opened before an entry was
		/// removed — resolves to a default ruleset rather than dropping the request, because the
		/// alternative is an instance nobody can enter and a panel that cannot describe itself.
		/// Callers that need to know whether the index was real use <see cref="IsValidDifficulty"/>.
		/// </remarks>
		/// <param name="index">Difficulty index, normally from a scene row.</param>
		/// <returns>The difficulty at that index, or a default ruleset.</returns>
		public DungeonDifficultyDefinition GetDifficulty(int index)
		{
			if (Difficulties != null &&
				index >= 0 &&
				index < Difficulties.Count &&
				Difficulties[index] != null)
			{
				return Difficulties[index];
			}

			return DefaultDifficulty;
		}

		/// <summary>
		/// Whether an index names a difficulty this dungeon actually offers.
		/// </summary>
		/// <remarks>
		/// The gate for anything a client asks for. A request naming a difficulty outside the list
		/// is refused rather than clamped: clamping would quietly enter a player into a ruleset
		/// they did not choose, and on a dungeon whose top difficulty ends the run on one death
		/// that is not a rounding error.
		/// </remarks>
		public bool IsValidDifficulty(int index)
		{
			if (Difficulties == null || Difficulties.Count < 1)
			{
				// A dungeon with no list has exactly one difficulty, at index 0.
				return index == 0;
			}

			return index >= 0 && index < Difficulties.Count && Difficulties[index] != null;
		}

		/// <summary>
		/// The name of one difficulty, for display.
		/// </summary>
		public string GetDifficultyName(int index)
		{
			DungeonDifficultyDefinition difficulty = GetDifficulty(index);
			return string.IsNullOrWhiteSpace(difficulty.Name) ? "Normal" : difficulty.Name;
		}

		/// <summary>
		/// Finds the template describing one dungeon scene.
		/// </summary>
		/// <remarks>
		/// <para>
		/// The reverse of the entrance-to-template link, for code holding a scene name and nothing
		/// else — principally the scene server hosting a running instance, which needs the
		/// difficulty rules for what it loaded and has no entrance object to read them from.
		/// </para>
		/// <para>
		/// Backed by a lazily-built index over the template cache rather than a scan per call,
		/// because the callers are per-spawn and per-panel-refresh. The index is discarded whenever
		/// the cache's size changes, which is the cheap way to notice templates being loaded or
		/// unloaded without hooking either event — the count is the only thing that can change
		/// without a template being added or removed.
		/// </para>
		/// </remarks>
		/// <param name="sceneName">Dungeon scene name.</param>
		/// <returns>The template describing it, or null when none declares it.</returns>
		public static DungeonTemplate GetBySceneName(string sceneName)
		{
			if (string.IsNullOrEmpty(sceneName))
			{
				return null;
			}

			Dictionary<int, DungeonTemplate> cache = GetCache<DungeonTemplate>();
			if (cache == null || cache.Count < 1)
			{
				sceneNameIndex = null;
				return null;
			}

			if (sceneNameIndex == null || indexedTemplateCount != cache.Count)
			{
				var index = new Dictionary<string, DungeonTemplate>(cache.Count, StringComparer.Ordinal);
				foreach (var kvp in cache)
				{
					DungeonTemplate template = kvp.Value;
					if (template == null || string.IsNullOrEmpty(template.DungeonSceneName))
					{
						continue;
					}

					/* First declaration wins, and a duplicate is reported rather than silently
					 * overwriting. Two templates claiming one dungeon is an authoring mistake with
					 * a confusing symptom — the difficulty list a player is shown at the entrance
					 * would be one template's while the rules applied inside were the other's. */
					if (index.ContainsKey(template.DungeonSceneName))
					{
						Log.Warning("DungeonTemplate",
							$"More than one dungeon template declares the scene '{template.DungeonSceneName}'; using '{index[template.DungeonSceneName].name}' and ignoring '{template.name}'.");
						continue;
					}

					index.Add(template.DungeonSceneName, template);
				}

				sceneNameIndex = index;
				indexedTemplateCount = cache.Count;
			}

			return sceneNameIndex.TryGetValue(sceneName, out DungeonTemplate found) ? found : null;
		}

		/// <summary>Scene name to template index, rebuilt when the template cache changes size.</summary>
		private static Dictionary<string, DungeonTemplate> sceneNameIndex;

		/// <summary>Template count the index was built from. See <see cref="GetBySceneName"/>.</summary>
		private static int indexedTemplateCount;

		/// <summary>
		/// The ruleset used when a dungeon declares no difficulties, or names one that is missing.
		/// </summary>
		/// <remarks>
		/// Shared and never handed out for mutation. It is only ever read — nothing in the
		/// codebase writes to a difficulty definition at runtime — so one instance is enough, and
		/// allocating a fresh one per lookup would put an allocation on the NPC spawn path.
		/// </remarks>
		private static readonly DungeonDifficultyDefinition DefaultDifficulty = new DungeonDifficultyDefinition();

		/// <summary>
		/// Loads the dungeon artwork on the client when the template enters the cache.
		/// </summary>
		public override void OnLoad(string typeName, string resourceName, int resourceID)
		{
			base.OnLoad(typeName, resourceName, resourceID);

			if (typeName != nameof(DungeonTemplate))
			{
				return;
			}

#if !UNITY_SERVER
			if (IconReference != null && IconReference.RuntimeKeyIsValid())
			{
				IconReference.LoadAssetAsync<Sprite>().Completed += (handle) =>
				{
					if (handle.Status == AsyncOperationStatus.Succeeded)
					{
						loadedIcon = handle.Result;
					}
				};
			}
#endif
		}

		/// <summary>
		/// Releases the dungeon artwork when the template leaves the cache.
		/// </summary>
		public override void OnUnload(string typeName, string resourceName, int resourceID)
		{
			if (typeName == nameof(DungeonTemplate))
			{
#if !UNITY_SERVER
				if (IconReference != null && IconReference.IsValid())
				{
					IconReference.ReleaseAsset();
				}
				loadedIcon = null;
#endif
			}

			base.OnUnload(typeName, resourceName, resourceID);
		}
	}
}
