using System;
using FishMMO.Server.Core;
using UnityEngine;

namespace FishMMO.Server.Implementation.World.SceneServer.Spawner
{
	/// <summary>
	/// The scene server's spawner system: populates every loaded world scene from its baked
	/// <see cref="SceneSpawnTable"/> and drives respawns.
	/// </summary>
	/// <remarks>
	/// Replaces the scene-placed spawner network objects. The tables are server-only data, so a
	/// client build never learns what spawns where.
	/// </remarks>
	[CreateAssetMenu(fileName = "SpawnerSystem", menuName = "FishMMO/Server/Scene Server/Spawner System", order = 1)]
	public class SpawnerSystem : ServerBehaviour
	{
		/// <summary>
		/// Every world scene's baked spawn table.
		/// </summary>
		[Tooltip("Every world scene's baked spawn table. Generated by FishMMO Dashboard → World → Spawn Tables → Rebuild Spawn Tables.")]
		public SpawnTableCatalogue Catalogue;

		/// <summary>
		/// The running host, or null before initialisation.
		/// </summary>
		public SpawnerHost Host { get; private set; }

		/// <inheritdoc />
		public override ServerComponentInitializationStatus InitializeOnce()
		{
			if (Server == null)
			{
				return ServerComponentInitializationStatus.FailedToFindServer;
			}

			FishNet.Managing.NetworkManager networkManager = Server.NetworkWrapper?.NetworkManager;
			if (networkManager == null)
			{
				return ServerComponentInitializationStatus.FailedToFindServerManager;
			}

			if (Catalogue == null)
			{
				FishMMO.Logging.Log.Warning("SpawnerSystem", "No spawn table catalogue is assigned; world scenes will load empty. Run FishMMO Dashboard → World → Spawn Tables → Rebuild Spawn Tables.");
			}

			Host = new SpawnerHost(networkManager, Catalogue);
			Host.Start();

			return ServerComponentInitializationStatus.Initialized;
		}

		/// <inheritdoc />
		public override void OnDeinitialize()
		{
			Host?.Stop();
			Host = null;
			SpawnerPool.Clear();
		}

		/// <inheritdoc />
		protected override void OnUpdate(float deltaTime)
		{
			Host?.Tick(DateTime.UtcNow, Time.time);
		}
	}
}
