using System;
using System.Text;
using FishMMO.Client.Security;

namespace FishMMO.Client
{
	/// <summary>
	/// Holds the compiled-in shared secret used by <see cref="ClientApiSigner"/>
	/// to sign requests against the FishMMO public web endpoints.
	///
	/// <para>
	/// IMPORTANT: This secret is NOT a credential. It is embedded in the
	/// shipped client binary and can be recovered by anyone with the build,
	/// so it should never be relied on for authentication or authorization.
	/// Its job is to filter generic crawlers / port-scanners / opportunistic
	/// abuse traffic and to detect blatant header forgery. Real authority
	/// always comes from the SRP-derived session token issued by the auth
	/// server, NOT from this header.
	/// </para>
	/// <para>
	/// The secret value lives in <see cref="GeneratedClientSecret.Secret"/>
	/// (ClientApiSecret.generated.cs), which is generated by the
	/// FishMMO > Security > Fetch Client Secrets editor tool.
	/// FishMMO > Security > Fetch Client Secrets editor tool. The committed
	/// release builds that still contain the sentinel.
	/// </para>
	/// </summary>
	internal static class ClientApiSecret
	{
		/// <summary>
		/// The shared secret. Read from the build-time-generated
		/// <see cref="GeneratedClientSecret.Secret"/> so the editor tool can write
		/// the real value without touching this file.
		/// </summary>
		private const string secretLiteral = GeneratedClientSecret.Secret;

#if !UNITY_EDITOR && !DEVELOPMENT_BUILD
		/// <summary>
		/// True when the sentinel placeholder API secret is still active
		/// in a release build. Checked by ClientSecurityBuildValidator.
		/// </summary>
		public static bool IsPlaceholderSecret { get; private set; }

		static ClientApiSecret()
		{
			if (secretLiteral.Contains(GeneratedPinSet.SentinelMarker))
			{
				IsPlaceholderSecret = true;
				throw new InvalidOperationException(
					"API gate secret is the sentinel placeholder. " +
					"The build validator should have blocked this build. " +
					"Use FishMMO > Security > Fetch Client Secrets and rebuild.");
			}
		}
#else
		/// <summary>
		/// In editor/dev builds, the sentinel secret is acceptable —
		/// the gate provides no protection, but local development works.
		/// </summary>
		public static bool IsPlaceholderSecret =>
			secretLiteral.Contains(GeneratedPinSet.SentinelMarker);
#endif

		/// <summary>
		/// Returns the secret as a fresh UTF-8 byte array. Callers SHOULD zero
		/// the buffer after use; this method exists so the secret string is
		/// not pinned in interned-string form longer than necessary.
		/// </summary>
		public static byte[] GetBytes()
		{
			return Encoding.UTF8.GetBytes(secretLiteral);
		}
	}
}
