#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;

namespace FishMMO.Shared.WorldDesign
{
	/// <summary>
	/// Regenerates the procedural biome art — payload, wrappers and built terrain layers — by itself
	/// after every script reload when any of it is missing or stale, so a fresh clone (or a machine
	/// whose generator code just changed) draws the same ground, rocks and trees as every other, and
	/// resolves every committed reference to generated art, with no manual step.
	/// </summary>
	/// <remarks>
	/// <para>
	/// <b>The check is cheap; the work is a job.</b> Looking costs a source hash and one file-exists
	/// per generated path (<see cref="ProceduralArtPayload.Check"/>). Only when something is missing
	/// or the generator has changed does it start <see cref="BiomeArtGenerator.StartGenerate"/>: one
	/// step per editor update behind a cancellable progress bar, like the world map bake.
	/// </para>
	/// <para>
	/// <b>Wrappers too.</b> Since 2026-10-02 nothing generated is committed: the terrain layers,
	/// materials and prefabs are build output with path-derived IDs like the payload, so the automatic
	/// pass builds missing ones, and rebuilds all of them when the generator changed
	/// (<see cref="ProceduralArtMode.Full"/>; files whose bytes come out the same are not rewritten).
	/// Generated art left over from before deterministic IDs is migrated first
	/// (<see cref="ProceduralArtMigration"/>), which may ask to save an open scene that references it.
	/// </para>
	/// <para>
	/// <b>It never runs</b> in batch mode (the build tool generates explicitly, and test runs must
	/// not be held up), in play mode, during a build or the world map bake, or while a generation
	/// already runs. While compiling or importing it waits and looks again. Cancelling the job
	/// stops it asking until the editor is restarted.
	/// </para>
	/// </remarks>
	[InitializeOnLoad]
	public static class ProceduralArtAutoGenerate
	{
		private const string DeclinedKey = "FishMMO.ProceduralArt.AutoGenerateDeclined";

		private static bool scheduled;

		static ProceduralArtAutoGenerate()
		{
			Schedule();
		}

		private static void Schedule()
		{
			if (scheduled)
			{
				return;
			}
			scheduled = true;
			EditorApplication.delayCall += Run;
		}

		private static void Run()
		{
			scheduled = false;
			if (Application.isBatchMode || BuildPipeline.isBuildingPlayer || TerrainArrayAutoBake.BuildRunning
				|| EditorApplication.isPlayingOrWillChangePlaymode || BiomeArtGenerator.IsBusy
				|| FishMMO.Shared.WorldMaps.WorldMapBaker.IsBusy || SessionState.GetBool(DeclinedKey, false))
			{
				return;
			}
			if (EditorApplication.isCompiling || EditorApplication.isUpdating || TerrainArrayBaker.IsBusy)
			{
				// Transient: look again once it has settled.
				Schedule();
				return;
			}

			int seed = ProceduralArtCatalogue.DefaultSeed;
			ProceduralArtPayload.State state = ProceduralArtPayload.Check(seed);
			if (!state.Stale)
			{
				return;
			}
			if (!state.StaleArt)
			{
				// Only the indirect variant collection (an authored material's keywords changed): no generation needed.
				ProceduralArtVariants.Ensure();
				return;
			}
			// An empty texture slot is only rewritten by a full pass (a missing-only one leaves existing files alone).
			ProceduralArtMode mode = state.NeedsFull ? ProceduralArtMode.Full : ProceduralArtMode.MissingOnly;
			string why = state.ToString();
			Debug.Log($"[Biome art] Regenerating procedural biome art ({mode}): {why}.");
			BiomeArtGenerator.StartGenerate(mode, seed, report =>
			{
				if (report != null && !report.Completed && report.Stopped != null && report.Stopped.StartsWith("cancelled", System.StringComparison.Ordinal))
				{
					SessionState.SetBool(DeclinedKey, true);
					Debug.LogWarning("[Biome art] Biome art generation cancelled; it will not start by itself again until the editor restarts. Run Dashboard → Biome Tools → Generate missing biome art (or Generate biome art) when convenient.");
					return;
				}
				// A run that could not fix it (a shader missing, a GUID taken) would otherwise repeat after every reload.
				ProceduralArtPayload.State after = ProceduralArtPayload.Check(seed);
				if (after.Stale)
				{
					SessionState.SetBool(DeclinedKey, true);
					Debug.LogWarning($"[Biome art] The procedural art is still stale after regenerating ({after}); see the report above. It will not retry by itself until the editor restarts.");
				}
			});
		}
	}
}
#endif
