using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace FishMMO.Client.Security.Editor
{
	/// <summary>
	/// Editor tool that writes the client gate secret to
	/// <c>Assets/Scripts/Client/Security/ClientApiSecret.generated.cs</c>.
	///
	/// <para>Open via <b>FishMMO &gt; Security &gt; Fetch Client Secrets</b>.</para>
	/// </summary>
	public sealed class ClientSecretTool : EditorWindow
	{
		private const string generatedFileName = "ClientApiSecret.generated.cs";

		private string gateSecretInput = "";
		private string statusMessage = "";
		private MessageType statusType = MessageType.None;
		private Vector2 scrollPosition;

		[MenuItem("FishMMO/Security/Fetch Client Secrets", priority = 101)]
		public static void ShowWindow()
		{
			var window = GetWindow<ClientSecretTool>(true, "Client Secrets", true);
			window.minSize = new Vector2(450, 320);
			window.Show();
		}

		private void OnEnable()
		{
			LoadExistingSecret();
		}

		private void OnGUI()
		{
			scrollPosition = EditorGUILayout.BeginScrollView(scrollPosition);

			EditorGUILayout.LabelField("Client Secret Generator", EditorStyles.boldLabel);
			EditorGUILayout.Space();

			EditorGUILayout.HelpBox(
				"Paste the client gate secret (base64) obtained from the FishMMO Installer " +
				"output or directly from the deployment_secrets database. " +
				"The secret must be valid base64 and decode to at least 32 bytes.\n\n" +
				"The result is written to Assets/Scripts/Client/Security/" + generatedFileName + ".",
				MessageType.Info);

			EditorGUILayout.Space();

			// ── Current file status ──────────────────────────────────────

			EditorGUILayout.LabelField("Current Status", EditorStyles.boldLabel);
			string path = GetGeneratedFilePath();
			if (File.Exists(path))
			{
				EditorGUILayout.HelpBox(
					generatedFileName + " exists at:\n" + path,
					MessageType.Info);
			}
			else
			{
				EditorGUILayout.HelpBox(
					generatedFileName + " does not exist yet. It will be created at:\n" + path,
					MessageType.Warning);
			}

			EditorGUILayout.Space();

			// ── Secret input ─────────────────────────────────────────────

			EditorGUILayout.LabelField("Gate Secret", EditorStyles.boldLabel);
			EditorGUILayout.BeginHorizontal();
			gateSecretInput = EditorGUILayout.TextField(gateSecretInput);
			EditorGUILayout.EndHorizontal();

			if (!string.IsNullOrEmpty(gateSecretInput))
			{
				string masked = MaskSecret(gateSecretInput);
				EditorGUILayout.LabelField("Preview: " + masked);
			}

			EditorGUILayout.Space();

			// ── Buttons ──────────────────────────────────────────────────

			if (GUILayout.Button("Write to " + generatedFileName, GUILayout.Height(30)))
				WriteSecretToGeneratedFile();

			EditorGUILayout.BeginHorizontal();
			if (GUILayout.Button("Load Existing from " + generatedFileName, GUILayout.Height(20)))
				LoadExistingSecret();

			if (GUILayout.Button("Validate Build Config", GUILayout.Height(20)))
				ValidateBuildConfig();
			EditorGUILayout.EndHorizontal();

			EditorGUILayout.Space();

			// ── Status ───────────────────────────────────────────────────

			if (!string.IsNullOrEmpty(statusMessage))
				EditorGUILayout.HelpBox(statusMessage, statusType);

			EditorGUILayout.EndScrollView();
		}

		// ── Validation ──────────────────────────────────────────────────

		private static bool IsValidBase64Secret(string input)
		{
			if (string.IsNullOrWhiteSpace(input))
				return false;

			try
			{
				byte[] decoded = Convert.FromBase64String(input.Trim());
				return decoded.Length >= 32;
			}
			catch
			{
				return false;
			}
		}

		private static string MaskSecret(string secret)
		{
			if (string.IsNullOrEmpty(secret))
				return "";

			if (secret.Length <= 8)
				return new string('*', secret.Length);

			return secret.Substring(0, 4) + new string('*', secret.Length - 8) + secret.Substring(secret.Length - 4);
		}

		// ── File I/O ──────────────────────────────────────────────────

		private void WriteSecretToGeneratedFile()
		{
			try
			{
				if (!IsValidBase64Secret(gateSecretInput))
				{
					statusMessage = "Invalid secret. Must be valid base64 and decode to at least 32 bytes.";
					statusType = MessageType.Error;
					Repaint();
					return;
				}

				string secret = gateSecretInput.Trim();

				string path = GetGeneratedFilePath();
				string dir = Path.GetDirectoryName(path);
				if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
					Directory.CreateDirectory(dir);

				var sb = new StringBuilder();
				sb.AppendLine("// AUTO-GENERATED by FishMMO > Security > Fetch Client Secrets");
				sb.AppendLine("// Generated at: " + DateTime.UtcNow.ToString("O"));
				sb.AppendLine();
				sb.AppendLine("namespace FishMMO.Client.Security");
				sb.AppendLine("{");
				sb.AppendLine("\tpublic static class GeneratedClientSecret");
				sb.AppendLine("\t{");
				sb.AppendLine("\t\tpublic const string Secret = \"" + secret + "\";");
				sb.AppendLine("\t}");
				sb.AppendLine("}");

				File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
				AssetDatabase.Refresh();

				statusMessage = "Wrote secret to " + generatedFileName;
				statusType = MessageType.Info;
			}
			catch (Exception ex)
			{
				statusMessage = "Failed to write generated file: " + ex.Message;
				statusType = MessageType.Error;
			}
			Repaint();
		}

		private void LoadExistingSecret()
		{
			string path = GetGeneratedFilePath();
			if (!File.Exists(path))
			{
				statusMessage = generatedFileName + " does not exist yet. Paste a gate secret, then write the file.";
				statusType = MessageType.Info;
				gateSecretInput = "";
				Repaint();
				return;
			}

			try
			{
				string content = File.ReadAllText(path);
				string parsed = ParseSecretFromGeneratedFile(content);
				if (!string.IsNullOrEmpty(parsed))
				{
					gateSecretInput = parsed;
					statusMessage = "Loaded existing secret from " + generatedFileName;
					statusType = MessageType.Info;
				}
				else
				{
					statusMessage = "Could not parse secret from " + generatedFileName + ". File may be empty or corrupt.";
					statusType = MessageType.Warning;
				}
			}
			catch (Exception ex)
			{
				statusMessage = "Failed to read " + generatedFileName + ": " + ex.Message;
				statusType = MessageType.Error;
			}
			Repaint();
		}

		/// <summary>
		/// Extracts the secret string from the generated C# file.
		/// </summary>
		private static string ParseSecretFromGeneratedFile(string content)
		{
			const string secretPrefix = "public const string Secret = \"";
			int start = content.IndexOf(secretPrefix, StringComparison.Ordinal);
			if (start < 0) return null;

			start += secretPrefix.Length;
			int end = content.IndexOf("\";", start, StringComparison.Ordinal);
			if (end < 0) return null;

			return content.Substring(start, end - start);
		}

		// ── Build validation ──────────────────────────────────────────

		private void ValidateBuildConfig()
		{
			statusMessage = "";
			statusType = MessageType.None;

			string path = GetGeneratedFilePath();
			if (!File.Exists(path))
			{
				statusMessage = generatedFileName + " does not exist. Write the secret file first.";
				statusType = MessageType.Error;
				Repaint();
				return;
			}

			string content = File.ReadAllText(path);
			string secret = ParseSecretFromGeneratedFile(content);

			if (string.IsNullOrEmpty(secret))
			{
				statusMessage = "Could not parse secret from " + generatedFileName + ".";
				statusType = MessageType.Error;
			}
			else if (!IsValidBase64Secret(secret))
			{
				statusMessage = "Secret in " + generatedFileName + " is not valid base64 or is less than 32 bytes.";
				statusType = MessageType.Error;
			}
			else
			{
				statusMessage = "Build config is valid. Secret is properly configured.";
				statusType = MessageType.Info;
			}

			Repaint();
		}

		// ── Helpers ───────────────────────────────────────────────────

		private static string GetGeneratedFilePath()
		{
			// Resolve relative to the project Assets folder.
			return Path.Combine(Application.dataPath,
				"Scripts", "Client", "Security", generatedFileName);
		}
	}
}
