using System;
using System.IO;
using FishMMO.Shared;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace FishMMO.Client.Security.Editor
{
	/// <summary>
	/// Blocks release client builds when security configuration is incomplete.
	///
	/// Four-tier check:
	///   1. <c>CertificatePins.generated.cs</c> has ≥2 non-sentinel pins (generated by FishMMO Dashboard > Game Settings).
	///   2. <c>ClientApiSecret.generated.cs</c> does not contain the sentinel (generated by FishMMO Dashboard > Game Settings).
	///   3. <c>HostConfig.generated.cs</c> does not contain the sentinel (generated by FishMMO Dashboard > Game Settings).
	///   4. <c>StreamingAssets/client-security.json</c> does NOT exist (anti-pattern).
	///
	/// Plus one WARNING-level check (does not block the build):
	///   5. <c>GeneratedPinSet.VersionManifestPublicKeyBase64</c> is configured, so the
	///      <c>/latest_version</c> manifest — which carries the only integrity check applied to
	///      a patch archive — is verified rather than merely transported.
	/// </summary>
	public sealed class ClientSecurityBuildValidator : IPreprocessBuildWithReport
	{
		/// <inheritdoc/>
		public int callbackOrder => 0;

		/// <inheritdoc/>
		public void OnPreprocessBuild(BuildReport report)
		{
			// Only enforce for non-development client builds.
			//
			// Check both signals:
			// 1) EditorUserBuildSettings.development — Player Settings / Build Window toggle
			// 2) BuildOptions.Development on this BuildPlayer request — CustomBuildTool sets
			//    this when Working Environment is Development, without always flipping the
			//    EditorUser flag. Skipping only (1) incorrectly blocked Dashboard "Development"
			//    builds that still had sentinel TLS pins (BuildFailedException pin gate).
			if (EditorUserBuildSettings.development)
				return;

			if (report != null && (report.summary.options & BuildOptions.Development) != 0)
				return;

			int realPinCount = ClientSecurityBootstrap.DefaultPinCount;
			if (realPinCount < 2)
			{
				throw new BuildFailedException(
					"Production build blocked: TLS certificate pins not configured.\n" +
					$"  Only {realPinCount} real pin(s) found in CertificatePins.generated.cs.\n" +
					"  Minimum 2 (active + backup) required for release builds.\n\n" +
					"  To fix:\n" +
					"    FishMMO Dashboard > Game Settings\n" +
					"    or use FishMMO Dashboard > Game Settings to configure real pins.");
			}

			if (GeneratedPinSetUsesSentinel())
			{
				throw new BuildFailedException(
					"Production build blocked: CertificatePins.generated.cs still contains\n" +
					"  sentinel placeholder values. CI must substitute real pins before\n" +
					"  building. Use FishMMO Dashboard > Game Settings.");
			}

			if (ClientApiSecretUsesSentinel())
			{
				throw new BuildFailedException(
					"Production build blocked: ClientApiSecret.generated.cs still contains\n" +
					"  the sentinel placeholder. CI must substitute the real gate secret before\n" +
					"  building. Use FishMMO Dashboard > Game Settings.");
			}

			if (HostConfigUsesSentinel())
			{
				throw new BuildFailedException(
					"Production build blocked: HostConfig.generated.cs still contains\n" +
					"  sentinel placeholder values. CI must substitute real host values\n" +
					"  before building, or configure them via:\n" +
					"    FishMMO Dashboard > Game Settings\n" +
					"  CI env vars: FISHMMO_API_HOST, FISHMMO_GAME_HOST, FISHMMO_PLAY_HOST,\n" +
					"  FISHMMO_ROOT_DOMAIN.");
			}

			/* Version-manifest signing: reported, not enforced.
			 *
			 * This is the one check here that warns rather than throwing, and the asymmetry is
			 * deliberate. The other four gate values that CI has always substituted, so failing
			 * the build on them tells an operator their pipeline is broken. This one gates a
			 * capability that did not exist until the S4 fix, so every existing deployment has
			 * it empty — throwing would mean shipping a change that breaks every release build
			 * in the project on the day it lands, for a posture that is no worse than the one
			 * they already had.
			 *
			 * The runtime is louder than this: HttpPatchServerService logs at Error on EVERY
			 * version check in a release build while the key is absent. Once a key IS
			 * configured, an unverifiable manifest is refused outright. This line exists so an
			 * operator learns about it at build time rather than from a player's log.
			 *
			 * Promote it to a BuildFailedException once the patch server signs its manifests.
			 */
			if (string.IsNullOrEmpty(GeneratedPinSet.VersionManifestPublicKeyBase64) ||
				GeneratedPinSet.VersionManifestPublicKeyBase64.Contains(GeneratedPinSet.SentinelMarker))
			{
				Debug.LogWarning(
					"FishMMO security: the version manifest is UNSIGNED in this release build.\n" +
					"  GeneratedPinSet.VersionManifestPublicKeyBase64 is not configured, so\n" +
					"  GET {APIHost}latest_version is trusted on the strength of TLS alone — including\n" +
					"  the SHA-256 that is the only integrity check applied to the patch archive.\n" +
					"  To fix: sign the /latest_version response with Ed25519 (same canonical form as the\n" +
					"  pin manifest) and embed the public key in CertificatePins.generated.cs.");
			}

			string streamingAssetsPinPath = Path.Combine(
				Application.streamingAssetsPath, "client-security.json");
			if (File.Exists(streamingAssetsPinPath))
			{
				throw new BuildFailedException(
					"Production build blocked: Obsolete StreamingAssets/client-security.json\n" +
					"  still exists. TLS pins are now IL-embedded via CertificatePins.generated.cs.\n" +
					"  Delete StreamingAssets/client-security.json and its .meta file.");
			}
		}

		private static bool GeneratedPinSetUsesSentinel()
		{
			string[] pins = GeneratedPinSet.Pins;
			if (pins == null) return true;
			foreach (var pin in pins)
			{
				if (pin != null && pin.Contains(GeneratedPinSet.SentinelMarker))
					return true;
			}
			return false;
		}

		private static bool ClientApiSecretUsesSentinel()
		{
			return GeneratedClientSecret.Secret.Contains(GeneratedPinSet.SentinelMarker);
		}

		private static bool HostConfigUsesSentinel()
		{
			string marker = GeneratedHostConfig.SentinelMarker;
			return GeneratedHostConfig.ApiHost.Contains(marker) ||
				GeneratedHostConfig.GameHost.Contains(marker) ||
				GeneratedHostConfig.PlayHost.Contains(marker) ||
				GeneratedHostConfig.RootDomain.Contains(marker);
		}
	}
}
