using System;
using System.IO;
using FishMMO.Shared;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace FishMMO.Client.Security.Editor
{
	/// <summary>
	/// Blocks release client builds when security configuration is incomplete.
	///
	/// Four-tier check:
	///   1. <c>CertificatePins.generated.cs</c> has ≥2 non-sentinel pins (generated by FishMMO Dashboard > Game Settings).
	///   2. <c>ClientApiSecret.generated.cs</c> does not contain the sentinel (generated by FishMMO Dashboard > Game Settings).
	///   3. <c>HostConfig.generated.cs</c> does not contain the sentinel (generated by FishMMO Dashboard > Game Settings).
	///   4. <c>StreamingAssets/client-security.json</c> does NOT exist (anti-pattern).
	/// </summary>
	public sealed class ClientSecurityBuildValidator : IPreprocessBuildWithReport
	{
		/// <inheritdoc/>
		public int callbackOrder => 0;

		/// <inheritdoc/>
		public void OnPreprocessBuild(BuildReport report)
		{
			// Only enforce for non-development client builds.
			if (EditorUserBuildSettings.development)
				return;

			int realPinCount = ClientSecurityBootstrap.DefaultPinCount;
			if (realPinCount < 2)
			{
				throw new BuildFailedException(
					"Production build blocked: TLS certificate pins not configured.\n" +
					$"  Only {realPinCount} real pin(s) found in CertificatePins.generated.cs.\n" +
					"  Minimum 2 (active + backup) required for release builds.\n\n" +
					"  To fix:\n" +
					"    FishMMO Dashboard > Game Settings\n" +
					"    or use FishMMO Dashboard > Game Settings to configure real pins.");
			}

			if (GeneratedPinSetUsesSentinel())
			{
				throw new BuildFailedException(
					"Production build blocked: CertificatePins.generated.cs still contains\n" +
					"  sentinel placeholder values. CI must substitute real pins before\n" +
					"  building. Use FishMMO Dashboard > Game Settings.");
			}

			if (ClientApiSecretUsesSentinel())
			{
				throw new BuildFailedException(
					"Production build blocked: ClientApiSecret.generated.cs still contains\n" +
					"  the sentinel placeholder. CI must substitute the real gate secret before\n" +
					"  building. Use FishMMO Dashboard > Game Settings.");
			}

			if (HostConfigUsesSentinel())
			{
				throw new BuildFailedException(
					"Production build blocked: HostConfig.generated.cs still contains\n" +
					"  sentinel placeholder values. CI must substitute real host values\n" +
					"  before building, or configure them via:\n" +
					"    FishMMO Dashboard > Game Settings\n" +
					"  CI env vars: FISHMMO_API_HOST, FISHMMO_GAME_HOST, FISHMMO_PLAY_HOST,\n" +
					"  FISHMMO_ROOT_DOMAIN.");
			}

			string streamingAssetsPinPath = Path.Combine(
				Application.streamingAssetsPath, "client-security.json");
			if (File.Exists(streamingAssetsPinPath))
			{
				throw new BuildFailedException(
					"Production build blocked: Obsolete StreamingAssets/client-security.json\n" +
					"  still exists. TLS pins are now IL-embedded via CertificatePins.generated.cs.\n" +
					"  Delete StreamingAssets/client-security.json and its .meta file.");
			}
		}

		private static bool GeneratedPinSetUsesSentinel()
		{
			string[] pins = GeneratedPinSet.Pins;
			if (pins == null) return true;
			foreach (var pin in pins)
			{
				if (pin != null && pin.Contains(GeneratedPinSet.SentinelMarker))
					return true;
			}
			return false;
		}

		private static bool ClientApiSecretUsesSentinel()
		{
			return GeneratedClientSecret.Secret.Contains(GeneratedPinSet.SentinelMarker);
		}

		private static bool HostConfigUsesSentinel()
		{
			string marker = GeneratedHostConfig.SentinelMarker;
			return GeneratedHostConfig.ApiHost.Contains(marker) ||
				GeneratedHostConfig.GameHost.Contains(marker) ||
				GeneratedHostConfig.PlayHost.Contains(marker) ||
				GeneratedHostConfig.RootDomain.Contains(marker);
		}
	}
}
