#!/bin/bash
# gen-fishmmo-stream-config.sh
# Regenerate NGINX stream configs for FishMMO game server UDP ports.
# Each game server port gets its own server {} block in the stream module.
# NGINX forwards raw UDP packets to loopback — game servers terminate QUIC/TLS.
#
# Usage:  ./gen-fishmmo-stream-config.sh
# After:  nginx -t && nginx -s reload  (zero-downtime reload)
#
# Port ranges:
#   7770-7779  Login Servers
#   7780-7789  World Servers
#   7790-7999  Scene Servers

set -euo pipefail

STREAM_DIR="${STREAM_DIR:-/etc/nginx/stream.d}"
BACKEND_IP="${BACKEND_IP:-127.0.0.1}"
LOGIN_START="${LOGIN_START:-7770}";   LOGIN_END="${LOGIN_END:-7779}"
WORLD_START="${WORLD_START:-7780}";   WORLD_END="${WORLD_END:-7789}"
SCENE_START="${SCENE_START:-7790}";   SCENE_END="${SCENE_END:-7999}"

mkdir -p "$STREAM_DIR"

# Generate into a temp directory, then atomically replace to avoid
# leaving partial configs if the script is killed mid-generation.
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

gen_port() {
    local port=$1 label=$2
    cat > "$TMPDIR/${label}-${port}.conf" <<EOF
# ${label} Server port ${port} (auto-generated by gen-fishmmo-stream-config.sh)
# QUIC/WebTransport is a long-lived, multiplexed, bidirectional protocol.
# proxy_responses is OMITTED (defaults to 0 = unlimited) so the session
# stays alive for the full game connection. proxy_timeout controls idle
# session reaping.
server {
    listen ${port} udp;
    proxy_pass ${BACKEND_IP}:${port};
    # QUIC idle timeout is 120s (WT_DEFAULT_IDLE_TIMEOUT_MS).  Keep the nginx
    # proxy_timeout within the same envelope so the UDP session is not held open
    # after the game server has already freed the connection.  Allow a 60s grace
    # period for clock skew and in-flight keepalives.
    proxy_timeout ${PROXY_TIMEOUT:-180s};
    # Upload/download limit per-session. Default 100 MB/s (~800 Mbps) should
    # comfortably saturate a 1 Gbps NIC for most deployments while preventing
    # a single UDP proxy session from starving others. Tune per deployment
    # based on available bandwidth, number of concurrent sessions, and
    # upstream game-server capacity.
    proxy_upload_rate 100m;
    proxy_download_rate 100m;
}
EOF
}

echo "Generating stream configs for ports: Login $LOGIN_START-$LOGIN_END, World $WORLD_START-$WORLD_END, Scene $SCENE_START-$SCENE_END..."

for port in $(seq $LOGIN_START $LOGIN_END); do gen_port "$port" "login"; done
for port in $(seq $WORLD_START $WORLD_END); do gen_port "$port" "world"; done
for port in $(seq $SCENE_START $SCENE_END); do gen_port "$port" "scene"; done

# Validate new configs BEFORE removing the old ones.
# This prevents leaving nginx with no stream configs if the generated
# configs are invalid (e.g. due to a scripting error).
echo "Validating generated configs..."
if ! nginx -t -c /etc/nginx/nginx.conf 2>/dev/null; then
    # Test with the new configs in a temp include path to isolate stream.d
    TMP_NGINX_CONF=$(mktemp)
    cat > "$TMP_NGINX_CONF" <<'NGINX_EOF'
events { worker_connections 1024; }
stream { include STREAM_DIR_PLACEHOLDER/*.conf; }
NGINX_EOF
    sed -i "s|STREAM_DIR_PLACEHOLDER|$TMPDIR|" "$TMP_NGINX_CONF"
    if nginx -t -c "$TMP_NGINX_CONF" 2>/dev/null; then
        echo "Generated configs validated OK."
    else
        echo "ERROR: Generated stream configs failed nginx validation. Old configs preserved." >&2
        rm -f "$TMP_NGINX_CONF"
        exit 1
    fi
    rm -f "$TMP_NGINX_CONF"
fi

# Atomically replace live configs — move new ones in FIRST, then remove stale.
# This avoids a window where zero configs exist if the script is interrupted
# between rm and mv (previous pattern). Even if interrupted mid-loop, nginx
# retains its previously loaded config for existing worker processes.
#
# Save the list of newly generated config filenames so we can identify stale ones.
ls "$TMPDIR" > "$TMPDIR/.generated-files"

# Move new configs in (atomic per-file — no window with zero configs)
for f in "$TMPDIR"/*.conf; do
    mv "$f" "$STREAM_DIR/"
done

# Remove stale configs that are no longer in the generated set
for f in "$STREAM_DIR"/*.conf; do
    if ! grep -qxF "$(basename "$f")" "$TMPDIR/.generated-files"; then
        rm -f "$f"
    fi
done

echo "Generated $(ls "$STREAM_DIR"/*.conf 2>/dev/null | wc -l) stream configs in $STREAM_DIR"
