using System.Security;
using SecureRemotePassword;

namespace FishMMO.Auth.Implementation
{
	/// <summary>
	/// Holds SRP (Secure Remote Password) authentication data and logic for a client-side session.
	/// </summary>
	/// <remarks>
	/// <b>String zeroization limitation:</b> SRP values (username, salt, verifier, ephemeral,
	/// proof, private key) are .NET immutable strings that cannot be deterministically zeroed.
	/// The SecureRemotePassword library requires string parameters throughout its API.
	/// <see cref="Clear"/> nulls all references so the GC can collect them, but the string
	/// contents remain in managed heap memory until garbage-collected. This limitation applies
	/// to all methods in this class, including <see cref="GetSaltAndVerifier"/> and
	/// <see cref="GetProof"/> where derived private keys are short-lived locals.
	/// <para/>
	/// <b>Thread safety:</b> This class is <b>not</b> thread-safe. <see cref="GetProof"/>,
	/// <see cref="Verify"/>, and <see cref="Clear"/> must not be called concurrently.
	/// In particular, <see cref="Clear"/> nulls <see cref="ClientEphemeral"/> and
	/// <see cref="Session"/>, which would cause <see cref="NullReferenceException"/> if
	/// another thread is mid-call in <see cref="GetProof"/> or <see cref="Verify"/>.
	/// The expected usage is single-threaded per connection.
	/// </remarks>
	public class ClientSrpData
	{
		private const string srpSessionNull = "Srp session is null.";
		private const string srpSuccess = "Srp Successfully verified session.";
		private const string srpProofFailed = "Srp failed to generate proof.";
		private const string srpVerifyFailed = "Srp failed to verify session.";

		/// <summary>
		/// The SRP client instance used for authentication operations.
		/// </summary>
		public SrpClient? SrpClient { get; private set; }
		/// <summary>
		/// The ephemeral values generated by the client for SRP authentication.
		/// </summary>
		public SrpEphemeral? ClientEphemeral { get; private set; }
		/// <summary>
		/// The current SRP session, containing proof and session keys.
		/// </summary>
		public SrpSession? Session { get; private set; }

		/// <summary>
		/// Constructs a new ClientSrpData instance and initializes the SRP client and ephemeral values.
		/// </summary>
		/// <param name="parameters">SRP parameters used for cryptographic operations.</param>
		public ClientSrpData(SrpParameters parameters)
		{
			SrpClient = new SrpClient(parameters);
			ClientEphemeral = SrpClient.GenerateEphemeral();
		}

		/// <summary>
		/// Generates a salt and verifier for the given username and password.
		/// Used for account registration or password changes.
		/// </summary>
		/// <remarks>
		/// The derived <c>privateKey</c> string is a short-lived local that becomes eligible
		/// for GC collection when this method returns. It cannot be zeroed because .NET strings
		/// are immutable — see class-level remarks.
		/// </remarks>
		/// <param name="username">The username for which to generate the verifier.</param>
		/// <param name="password">The password for which to generate the verifier.</param>
		/// <param name="salt">Output salt value.</param>
		/// <param name="verifier">Output verifier value.</param>
		public void GetSaltAndVerifier(string username, string password, out string salt, out string verifier)
		{
			salt = SrpClient!.GenerateSalt();
			string privateKey = SrpClient.DerivePrivateKey(salt, username, password);
			verifier = SrpClient.DeriveVerifier(privateKey);
		}

		/// <summary>
		/// Generates a client proof for SRP authentication using provided credentials and server ephemeral value.
		/// </summary>
		/// <remarks>
		/// The derived <c>privateKey</c> string cannot be zeroed (immutable .NET string).
		/// On both success and exception paths the reference goes out of scope, making it
		/// GC-eligible. The exception handler does not log or expose <c>privateKey</c>.
		/// See class-level remarks for the broader string zeroization limitation.
		/// <para/>
		/// <b>Single-use:</b> Calling this method more than once overwrites <see cref="Session"/>
		/// with a freshly derived session. Callers that cached the proof from a prior call will
		/// hold a stale value. The intended protocol flow calls <see cref="GetProof"/> exactly
		/// once, followed by <see cref="Verify"/>, then <see cref="Clear"/>.
		/// </remarks>
		/// <param name="username">The username for authentication.</param>
		/// <param name="password">The password for authentication.</param>
		/// <param name="salt">The salt used for deriving the private key.</param>
		/// <param name="serverPublicEphemeral">The server's public ephemeral value.</param>
		/// <param name="proof">Output client proof if authentication succeeds; otherwise, an error message.</param>
		/// <returns>True if proof generation succeeded; otherwise, false.</returns>
		public bool GetProof(string username, string password, string salt, string serverPublicEphemeral, out string proof)
		{
			string privateKey = SrpClient!.DerivePrivateKey(salt, username, password);
			try
			{
				Session = SrpClient!.DeriveSession(ClientEphemeral!.Secret,
												  serverPublicEphemeral,
												  salt,
												  username,
												  privateKey);
				proof = Session!.Proof;
				return true;
			}
			catch (SecurityException)
			{
				proof = srpProofFailed;
				return false;
			}
		}

		/// <summary>
		/// Verifies the server's proof to complete the SRP authentication session.
		/// </summary>
		/// <param name="serverProof">The proof value provided by the server.</param>
		/// <param name="result">Output result message indicating success or reason for failure.</param>
		/// <returns>True if verification succeeded; otherwise, false.</returns>
		public bool Verify(string serverProof, out string result)
		{
			if (Session == null)
			{
				result = srpSessionNull;
				return false;
			}
			try
			{
				// Verifies the session using the client's ephemeral public value, session, and server proof.
				SrpClient!.VerifySession(ClientEphemeral!.Public, Session, serverProof);
				result = srpSuccess;
				return true;
			}
			catch (SecurityException)
			{
				result = srpVerifyFailed;
				return false;
			}
		}

		/// <summary>
		/// Clears all SRP references so the GC can collect sensitive SRP strings
		/// (salt, verifier, proofs, session keys) as early as possible.
		/// .NET strings cannot be deterministically zeroed, but nulling references
		/// removes the reachability root and allows collection.
		/// </summary>
		/// <remarks>
		/// Only fields stored on this instance are nulled. <c>SrpParameters</c> passed
		/// to the constructor is not retained as a field. If future fields are added,
		/// they must be nulled here as well.
		/// </remarks>
		public void Clear()
		{
			SrpClient = null;
			ClientEphemeral = null;
			Session = null;
		}
	}
}