using UnityEngine;
using UnityEngine.UIElements;
using FishMMO.Shared;
using FishMMO.Shared.Core;
using FishMMO.Logging;

namespace FishMMO.Client
{
	/// <summary>
	/// Displays another player character's name and equipment by reading their in-memory data
	/// directly. All character data is already synchronised to observers via
	/// WritePayload/ReadPayload, so no server round-trip is required.
	/// </summary>
	/// <remarks>
	/// Slots are built here rather than instantiated from a prefab, and reuse the shared
	/// <c>.fish-slot</c> classes so an inspected character's gear reads the same as the player's
	/// own equipment panel.
	///
	/// Each slot carries a tooltip, which an earlier version did not — it only set an icon and a
	/// name. Inspecting is for judging someone's gear, and the item name alone does not say what
	/// the item does; the tooltip text is already generated by the shared item code, so wiring it
	/// up costs nothing.
	/// </remarks>
	public class UITKInspect : UITKControl
	{
		/// <summary>Name of the label showing the inspected character's name.</summary>
		private const string NAME_LABEL_NAME = "inspect-name";

		/// <summary>Name of the container equipment slots are built into.</summary>
		private const string SLOT_LIST_NAME = "inspect-slot-list";

		/// <summary>Name of the close button.</summary>
		private const string CLOSE_BUTTON_NAME = "inspect-close-btn";

		/// <summary>Name of the label shown when the target has nothing equipped.</summary>
		private const string EMPTY_LABEL_NAME = "inspect-empty";

		/// <summary>USS class for a generated equipment slot.</summary>
		private const string SLOT_CLASS = "inspect-slot";

		/// <summary>USS class for a slot's icon element.</summary>
		private const string SLOT_ICON_CLASS = "inspect-slot__icon";

		/// <summary>USS class for a slot's name label.</summary>
		private const string SLOT_LABEL_CLASS = "inspect-slot__label";

		/// <summary>Label showing the inspected character's name.</summary>
		private Label nameLabel;

		/// <summary>Container equipment slots are built into.</summary>
		private VisualElement slotList;

		/// <summary>Label shown when the target has nothing equipped.</summary>
		private Label emptyLabel;

		/// <summary>Close button.</summary>
		private Button closeButton;

		/// <summary>
		/// The character last passed to <see cref="Inspect"/>.
		/// </summary>
		/// <remarks>
		/// Held so <see cref="OnAfterStarting"/> can rebuild the panel if the visual tree is
		/// replaced while it is open — otherwise the panel comes back correctly wired and empty.
		/// </remarks>
		private IPlayerCharacter inspected;

		/// <summary>
		/// Resolves elements and wires the close button.
		/// </summary>
		public override void OnStarting()
		{
			if (Root == null)
			{
				return;
			}

			nameLabel = Root.Q<Label>(NAME_LABEL_NAME);
			slotList = Root.Q<VisualElement>(SLOT_LIST_NAME);
			emptyLabel = Root.Q<Label>(EMPTY_LABEL_NAME);
			closeButton = Root.Q<Button>(CLOSE_BUTTON_NAME);

			if (slotList == null)
			{
				Log.Error("UITKInspect", "Slot list element is missing.");
			}

			if (closeButton != null)
			{
				closeButton.clicked -= Hide;
				closeButton.clicked += Hide;
			}
		}

		/// <summary>
		/// Rebuilds the panel from the last inspected character after a tree rebuild.
		/// </summary>
		protected override void OnAfterStarting()
		{
			if (inspected != null)
			{
				Populate(inspected);
			}
		}

		/// <summary>
		/// Populates the inspect panel with the target player's data and shows it.
		/// </summary>
		/// <param name="target">The player character to inspect.</param>
		public void Inspect(IPlayerCharacter target)
		{
			if (target == null || target.Transform == null)
			{
				return;
			}

			inspected = target;

			// Shown first so the visual tree exists before Populate looks for elements in it.
			Show();
			Populate(target);
		}

		/// <summary>
		/// Writes a character's name and equipment into the panel.
		/// </summary>
		/// <param name="target">The player character to display.</param>
		private void Populate(IPlayerCharacter target)
		{
			if (slotList == null)
			{
				return;
			}

			slotList.Clear();

			if (nameLabel != null)
			{
				nameLabel.text = target.CharacterName;
			}

			int shown = 0;
			if (target.TryGet(out IEquipmentController equipmentController))
			{
				for (int i = 0; i < equipmentController.Items.Count; ++i)
				{
					Item item = equipmentController.Items[i];
					if (item == null || item.Template == null)
					{
						continue;
					}

					slotList.Add(BuildSlot(item));
					++shown;
				}
			}

			if (emptyLabel != null)
			{
				emptyLabel.style.display = shown > 0 ? DisplayStyle.None : DisplayStyle.Flex;
			}
		}

		/// <summary>
		/// Builds one equipment slot element.
		/// </summary>
		/// <param name="item">The equipped item to display.</param>
		/// <returns>The slot element.</returns>
		private VisualElement BuildSlot(Item item)
		{
			VisualElement slot = new VisualElement();
			slot.AddToClassList("fish-slot");
			slot.AddToClassList(SLOT_CLASS);

			VisualElement icon = new VisualElement();
			icon.AddToClassList("fish-slot__icon");
			icon.AddToClassList(SLOT_ICON_CLASS);
			icon.pickingMode = PickingMode.Ignore;
			if (item.Template.Icon != null)
			{
				icon.style.backgroundImage = new StyleBackground(item.Template.Icon);
			}
			slot.Add(icon);

			Label label = new Label(item.Template.Name);
			label.AddToClassList("fish-slot__label");
			label.AddToClassList(SLOT_LABEL_CLASS);
			label.pickingMode = PickingMode.Ignore;
			slot.Add(label);

			string tooltip = item.Tooltip();
			if (!string.IsNullOrWhiteSpace(tooltip))
			{
				slot.RegisterCallback<PointerEnterEvent>(_ =>
				{
					if (UIManager.TryGetTK("UITooltip", out UITKTooltip uiTooltip))
					{
						uiTooltip.Open(tooltip);
					}
				});
				slot.RegisterCallback<PointerLeaveEvent>(_ =>
				{
					if (UIManager.TryGetTK("UITooltip", out UITKTooltip uiTooltip))
					{
						uiTooltip.Hide();
					}
				});
			}

			return slot;
		}

		/// <summary>
		/// Hides the panel and forgets the inspected character.
		/// </summary>
		/// <remarks>
		/// Overrides <c>Hide(bool)</c>, not <c>Hide()</c>. <c>Hide()</c> is non-virtual and only
		/// forwards here, so this is the one place teardown can live where every caller reaches
		/// it — quit-to-login calls the bool form directly.
		/// </remarks>
		public override void Hide(bool overrideIsAlwaysOpen)
		{
			/* Cleared so a later tree rebuild does not silently repopulate a panel the player
			 * closed, and so the character reference is not held past its usefulness. Guarded so
			 * a refused hide leaves the still-open panel's subject intact. */
			if (!overrideIsAlwaysOpen && Document != null)
			{
				inspected = null;
			}
			base.Hide(overrideIsAlwaysOpen);
		}
	}
}
